import "../styles/globals.css";
import Header from "../components/Header";
import Head from "next/head";
import React, { useCallback } from "react";

export const CartContext = React.createContext(null);

function MyApp({ Component, pageProps }) {
  const getCart = useCallback(() => {
    function _getCart() {
      return JSON.parse(window.localStorage.getItem("state"));
    }
    return _getCart;
  });

  const setCart = useCallback(() => {
    function _getCart() {
      return JSON.parse(window.localStorage.getItem("state"));
    }
    return _getCart;
  });

  const removeCart = useCallback(() => {
    function _getCart() {
      return JSON.parse(window.localStorage.getItem("state"));
    }
    return _getCart;
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CartContext.Provider value={getCart()}>
        <Component {...pageProps} />
      </CartContext.Provider>
    </>
  );
}

export default MyApp;
